name: utf7
description: Provides methods to encode/decode strings to/from the utf7 format as defined in rfc 2152
version: 0.2.1
homepage: https://github.com/michaelspiss/dart-utf7
author: Michael Spiss <michaelspiss.dev@mailbox.org>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.4
